# backend/app/api/insights_router.py

from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from typing import List, Dict, Any

from ..core.database import get_db
from ..models import user_model
from ..services import auth_service, insights_service # Import the new service
from ..schemas import insights_schema # <-- NEW IMPORT

router = APIRouter(
    prefix="/insights",
    tags=["Insights"],
    dependencies=[Depends(auth_service.get_current_user)]
)

@router.get("/burndown", response_model=List[Dict[str, Any]])
def get_burndown_data(
    db: Session = Depends(get_db),
    current_user: user_model.User = Depends(auth_service.get_current_user)
):
    """
    Retrieves data for the Predictive Progress (Burndown) Chart.
    Data is weighted by task priority score.
    """
    return insights_service.get_burndown_data(db, current_user.id)

@router.get("/heatmap", response_model=List[Dict[str, Any]])
def get_heatmap_data(
    db: Session = Depends(get_db),
    current_user: user_model.User = Depends(auth_service.get_current_user)
):
    """
    Retrieves data for the Productivity Heatmap.
    Data is generated by aggregating task completion logs by day of week and hour of day.
    """
    return insights_service.get_productivity_heatmap_data(db, current_user.id)

# --- NEW ENDPOINT ---
@router.get("/progress-summary", response_model=insights_schema.DashboardProgressSummary)
def get_dashboard_progress_summary(
    db: Session = Depends(get_db),
    current_user: user_model.User = Depends(auth_service.get_current_user)
):
    """
    Retrieves high-level progress stats for the main dashboard.
    """
    return insights_service.get_dashboard_progress(db, current_user.id)
# --- END OF NEW ENDPOINT ---