"""Add Google OAuth fields to user model

Revision ID: 3a13c42e229b
Revises: 5fa5d48dd25d
Create Date: 2025-11-03 14:46:39.872268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a13c42e229b'
down_revision: Union[str, Sequence[str], None] = '5fa5d48dd25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_oauth_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('our_app_refresh_token', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_our_app_refresh_token'), 'users', ['our_app_refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_our_app_refresh_token'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'our_app_refresh_token')
    op.drop_column('users', 'google_oauth_refresh_token')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
