"""Add has_finalized_signup flag to user

Revision ID: 3afd5e38fb9d
Revises: c8a250ea7beb
Create Date: 2025-11-03 15:19:33.134243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afd5e38fb9d'
down_revision: Union[str, Sequence[str], None] = 'c8a250ea7beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_finalized_signup', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'has_finalized_signup')
    # ### end Alembic commands ###
