"""Add ondelete SET NULL to user_logs.task_id

Revision ID: 7b62e1f19158
Revises: c99ad07ff1b4
Create Date: 2025-10-30 18:34:29.012278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b62e1f19158'
down_revision: Union[str, Sequence[str], None] = 'c99ad07ff1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('user_logs_task_id_fkey'), 'user_logs', type_='foreignkey')
    op.create_foreign_key(None, 'user_logs', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logs', type_='foreignkey')
    op.create_foreign_key(op.f('user_logs_task_id_fkey'), 'user_logs', 'tasks', ['task_id'], ['id'])
    op.alter_column('user_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
