"""Add gamification fields to user

Revision ID: 81398c30327e
Revises: 7b62e1f19158
Create Date: 2025-11-01 22:44:59.907725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81398c30327e'
down_revision: Union[str, Sequence[str], None] = '7b62e1f19158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_active_day', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('achievements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'achievements')
    op.drop_column('users', 'last_active_day')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
