"""Add summary cache fields to user

Revision ID: 92c2b4d08bad
Revises: 81398c30327e
Create Date: 2025-11-02 12:27:00.334857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c2b4d08bad'
down_revision: Union[str, Sequence[str], None] = '81398c30327e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_summary_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_summary_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_summary_generated_at')
    op.drop_column('users', 'last_summary_text')
    # ### end Alembic commands ###
