"""Add user_logs table for ML data collection

Revision ID: c99ad07ff1b4
Revises: c1d03b7521c3
Create Date: 2025-10-30 18:02:14.216814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99ad07ff1b4'
down_revision: Union[str, Sequence[str], None] = 'c1d03b7521c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
